import { chmodSync, existsSync, mkdirSync, writeFileSync, realpathSync, unlinkSync } from 'fs'
import { homedir } from 'os'
import { dirname, join } from 'path'
import { app } from 'electron'

/** 与 apps/extension/manifest.json 的 key 对应的稳定扩展 ID */
export const EXTENSION_ID = 'facimohbibpamgdkbigdabhomohndbla'
export const NATIVE_HOST_NAME = 'com.aitranslator.native'

/** 解析 native-host 内 host.mjs（开发态 getAppPath 可能指向 out/） */
function hostMjsCandidates(): string[] {
  const file = 'host.mjs'
  if (app.isPackaged) {
    return [join(process.resourcesPath, 'native-host', file)]
  }
  const out: string[] = []
  try {
    out.push(join(app.getAppPath(), 'native-host', file))
  } catch {
    // ignore
  }
  out.push(join(process.cwd(), 'native-host', file))
  out.push(join(process.cwd(), 'apps/desktop/native-host', file))
  // electron-vite main 编译到 out/main，上两级即 apps/desktop
  out.push(join(__dirname, '../../native-host', file))
  return out
}

function resolveHostMjs(): string {
  const candidates = hostMjsCandidates()
  let raw = candidates[0] ?? join(process.cwd(), 'native-host', 'host.mjs')
  for (const p of candidates) {
    if (existsSync(p)) {
      raw = p
      break
    }
  }
  try {
    return realpathSync(raw)
  } catch {
    return raw
  }
}

/**
 * Native Messaging 启动的可执行文件。
 * 打包后 macOS 优先用 Helper：避免 Chrome 拉起与主程序同名二进制时误激活 GUI。
 */
function resolveNodeRuntime(): string {
  if (process.platform === 'darwin' && app.isPackaged) {
    const exeDir = dirname(process.execPath)
    const name = 'AI Translator'
    const helper = join(
      exeDir,
      '../Frameworks',
      `${name} Helper.app`,
      'Contents/MacOS',
      `${name} Helper`
    )
    if (existsSync(helper)) return helper
  }
  return process.execPath
}

/**
 * Chrome 启动 Native Host 时 PATH 极短（无 nvm），`node` 常找不到。
 * 用 Electron 的 ELECTRON_RUN_AS_NODE 跑 host.mjs，不依赖系统 node。
 */
function writeGeneratedLauncher(hostMjs: string): string {
  const dir = join(homedir(), '.ai-translator')
  mkdirSync(dir, { recursive: true })
  const launcher = join(dir, process.platform === 'win32' ? 'run-host.cmd' : 'run-host.sh')
  const electronPath = resolveNodeRuntime()

  if (process.platform === 'win32') {
    // Windows：cmd 包装；仍依赖本机能跑 Electron
    const body = `@echo off\r\nset ELECTRON_RUN_AS_NODE=1\r\n"${electronPath}" "${hostMjs}"\r\n`
    writeFileSync(launcher, body, 'utf8')
  } else {
    const body = `#!/bin/bash
# Generated by AI Translator — do not edit
# Chrome Native Messaging 环境 PATH 不含 nvm；用 Electron 作 Node 运行时
export ELECTRON_RUN_AS_NODE=1
exec "${electronPath}" "${hostMjs}"
`
    writeFileSync(launcher, body, 'utf8')
    try {
      chmodSync(launcher, 0o755)
    } catch {
      // ignore
    }
  }
  return launcher
}

function hostDirs(): string[] {
  const home = homedir()
  if (process.platform === 'darwin') {
    return [
      join(home, 'Library/Application Support/Google/Chrome/NativeMessagingHosts'),
      join(home, 'Library/Application Support/Microsoft Edge/NativeMessagingHosts'),
      join(home, 'Library/Application Support/Chromium/NativeMessagingHosts')
    ]
  }
  if (process.platform === 'win32') {
    // Windows 还需写注册表；v1 先写用户级 JSON 路径，并在 README 注明
    return [join(home, 'AppData/Local/AI Translator/NativeMessagingHosts')]
  }
  return [
    join(home, '.config/google-chrome/NativeMessagingHosts'),
    join(home, '.config/microsoft-edge/NativeMessagingHosts'),
    join(home, '.config/chromium/NativeMessagingHosts')
  ]
}

/** 安装/更新 Chromium Native Messaging Host 清单（每次启动都应调用，刷新绝对路径） */
export function installNativeHostManifest(): { ok: boolean; path: string; error?: string } {
  const hostMjs = resolveHostMjs()
  if (!existsSync(hostMjs)) {
    return { ok: false, path: hostMjs, error: 'host.mjs not found' }
  }

  // 清单 path 指向生成的 launcher（内含 Electron 绝对路径），避免 Chrome PATH 无 node
  const hostPath = writeGeneratedLauncher(hostMjs)

  const manifest = {
    name: NATIVE_HOST_NAME,
    description: 'AI Translator native host for Cursor proxy',
    path: hostPath,
    type: 'stdio',
    allowed_origins: [`chrome-extension://${EXTENSION_ID}/`]
  }

  const dirs = hostDirs()
  let lastPath = ''
  try {
    for (const dir of dirs) {
      mkdirSync(dir, { recursive: true })
      lastPath = join(dir, `${NATIVE_HOST_NAME}.json`)
      writeFileSync(lastPath, JSON.stringify(manifest, null, 2), 'utf8')
    }
    return { ok: true, path: lastPath }
  } catch (err) {
    return {
      ok: false,
      path: lastPath,
      error: err instanceof Error ? err.message : String(err)
    }
  }
}

/** 退出时清掉 port 文件，避免扩展误判「有 port 但连不上」 */
export function clearNativeBridgePortFile(): void {
  try {
    unlinkSync(join(homedir(), '.ai-translator', 'native-bridge-port'))
  } catch {
    /* ignore */
  }
}
